n_cars: 300
k: 100
batch_size: 100
p: 0.5
seed: 42
n_events: 500000
chunk_size: 1000
design: 
  name: switchback
  switch_every: 3600 # in seconds
output: output/switchback/results
config_output: output/switchback/config